version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: tib
      POSTGRES_USER: tib
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: